export const SETCONFIG = 'SETCONFIG';
export const SETCOMPONENTS = 'SETCOMPONENTS';
export const SELECTITEM = 'SELECTITEM';
export const UPDATECOMPONENT = 'UPDATECOMPONENT';
export const REMOVECOMPONENT = 'REMOVECOMPONENT';
export const ADDCOMPONENT = 'ADDCOMPONENT';